### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by parames3010** [enarjord/passivbot_futures#9] opened 2021-01-17 04:16 UTC
![image](https://user-images.githubusercontent.com/8073243/104830835-0c159d00-58b5-11eb-8eab-42448132aff1.png)

Hello, I am having some problems I hope you can help, As you can see from the picture above.
This error happened after I move to the new VPS. this error only occurs bybit. For binance still working normally

**Comment by enarjord** [comment] 2021-01-17 12:42
i'm not sure what's going on here

'bybit' object has no attribute 'public_get_symbols'

'bybit' object is a ccxt bybit instance, if it doesn't have 'public_get_symbols', then maybe your ccxt installation is out of date.  try updating it

python3 -m pip install ccxt --upgrade

**Comment by parames3010** [comment] 2021-01-17 14:10
Thank you, I try upgrade ccxt and also upgrade all "python -m pip install matplotlib pandas websockets ccxt --upgrade"  
But it seems that the problem is not solved. :(

![image](https://user-images.githubusercontent.com/8073243/104845449-2b89e580-5908-11eb-8253-2e507f29c91b.png)

**Comment by enarjord** [comment] 2021-01-17 14:24
i tried initiating ccxt without api key/secret and i tried to call public_get_symbols without internet connection, but was unable to reproduce your error.  i don't know what's going on there.

you are doing the exact same steps, with the same files, on both your previous vps and the new one, and the new one only gives error? both are run on windows?

**Comment by parames3010** [comment] 2021-01-17 15:03
I'll text you to a telegram, maybe if you can help me check about vps

**Comment by johnbonesnj** [comment] 2021-01-17 16:56
I am having same issue on a few platforms. The bot works great on my Windows 10 laptop with python 3.8. But I get that exact error on a Windows server box running 3.8 and on a Ubuntu VPS using Python 3.8, both are fresh installs and all modules are up to date.

I believe its the async part of it, I am guessing that its trying to "get_public_symbols" before ccxt has returned a valid object. 
This line:
    info = await self.cc.public_get_symbols()
To me it seams that self.cc is undefined because previous async call hasn't been returned maybe?

I can't debug on the Linux vps right now but I will try to debug the file on the windows server and see.

**Comment by enarjord** [comment] 2021-01-17 17:08
the error was because of backwards incompatibility with the latest version of ccxt

it is fixed now

**Comment by johnbonesnj** [comment] 2021-01-17 17:08
Looking at it in a debugger, maybe there was a change to bybit or ccxt's API?

Because it looks like this may work:

self.cc.v2PublicGetSymbols()

**Comment by enarjord** [comment] 2021-01-17 17:09
that's right! you found the solution too

**Closed** 2021-01-18 02:56 UTC
